# Generated by Django 4.0.6 on 2022-09-07 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('highest_qualification', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=1000)),
                ('about_you', models.TextField()),
                ('upload_resume', models.FileField(upload_to='media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qualifications', models.TextField()),
                ('responsbilities', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='myapp.vacancy'),
        ),
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.application')),
            ],
        ),
    ]
