# Generated by Django 4.0.6 on 2022-09-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
